CREATE DATABASE Qulix;
GO
Use Qulix
CREATE TABLE Company
(
    Id INT,
    Name  NVARCHAR(20) PRIMARY KEY,
    Form NVARCHAR(20)
);

GO

CREATE TABLE Users
(
    Id INT PRIMARY KEY IDENTITY,
    Surname NVARCHAR(20) NOT NULL, 
    Name NVARCHAR(20) NOT NULL,
    Patronymic NVARCHAR(20) NOT NULL,
    Date DATE NOT NULL ,
    Position NVARCHAR(20) NOT NULL,
	Company NVARCHAR(20),
	FOREIGN KEY (Company)  REFERENCES Company (Name) ON DELETE CASCADE ON UPDATE CASCADE
);
